name: Pull TurboWarp UI Code
on:
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  pull-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Clone TurboWarp GUI files
        run: |
          gh repo clone TurboWarp/scratch-gui temp-tw -- --depth=1
          rsync -av --exclude='.git' --exclude='.github' temp-tw/ .
          rm -rf temp-tw
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Commit and Push to your repository
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Merged complete TurboWarp UI files into repository"
          git push origin main
